# Generated by Django 4.1.7 on 2023-03-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_users", "0004_alter_bloguser_first_name_alter_bloguser_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloguser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="bloguser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
