# Generated by Django 4.1.7 on 2023-03-01 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Topic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Post across whole site.', primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=254)),
                ('slug', models.SlugField(max_length=254)),
                ('content', models.TextField(help_text='Enter the content of your Post here', max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(blank=True, help_text='Select a Topic for this Post', to='blog_app.topic')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
