# Generated by Django 4.1.7 on 2023-03-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="anonymous", max_length=50)),
                (
                    "email",
                    models.EmailField(
                        default="anonymous@anonymous.com", max_length=100
                    ),
                ),
                ("body", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "active",
                    models.BooleanField(default=False, verbose_name="is published"),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=254)),
                ("slug", models.SlugField(max_length=254)),
                (
                    "content",
                    models.TextField(
                        help_text="Enter the content of your Post here",
                        max_length=10000,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("draft", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Topic")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
