# Generated by Django 4.1.7 on 2023-03-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_on"]},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created",
            new_name="created_on",
        ),
        migrations.AddField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog_app.post",
            ),
        ),
    ]
