# Generated by Django 4.1.7 on 2023-03-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0004_alter_comment_options_rename_content_comment_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="draft",
            field=models.BooleanField(default=True),
        ),
    ]
